INSERT INTO City (province_name, city_name) VALUES
('Tehran', 'Tehran'),
('Razavi Khorasan', 'Mashhad'),
('Isfahan', 'Isfahan'),
('Alborz', 'Karaj'),
('Fars', 'Shiraz'),
('East Azerbaijan', 'Tabriz'),
('Qom', 'Qom'),
('Khuzestan', 'Ahvaz'),
('Kermanshah', 'Kermanshah'),
('West Azerbaijan', 'Urmia'),
('Gilan', 'Rasht'),
('Sistan and Baluchestan', 'Zahedan'),
('Hamadan', 'Hamadan'),
('Kerman', 'Kerman'),
('Yazd', 'Yazd'),
('Ardabil', 'Ardabil'),
('Hormozgan', 'Bandar Abbas'),
('Markazi', 'Arak'),
('Zanjan', 'Zanjan');

INSERT INTO City (province_name, city_name) VALUES
('Kermanshah', 'Kermanshah'),
('Kohgiluyeh and Boyer-Ahmad', 'Yasuj'),
('Kurdistan', 'Sanandaj'),
('Lorestan', 'Khorramabad'),
('Mazandaran', 'Sari'),
('North Khorasan', 'Bojnord'),
('Qazvin', 'Qazvin'),
('Semnan', 'Semnan'),
('South Khorasan', 'Birjand'),
('West Azerbaijan', 'Khoy'),
('East Azerbaijan', 'Maragheh'),
('Golestan', 'Gorgan'),
('Hormozgan', 'Bandar Lengeh'),
('Ilam', 'Ilam'),
('Kerman', 'Bam'),
('Khorasan Razavi', 'Sabzevar'),
('Markazi', 'Saveh'),
('Mazandaran', 'Amol'),
('Qom', 'Qom'),
('Yazd', 'Meybod');

INSERT INTO City (province_name, city_name) VALUES
('East Azerbaijan', 'Marand'),
('Fars', 'Marvdasht'),
('Gilan', 'Bandar Anzali'),
('Golestan', 'Gonbad-e Kavus'),
('Hamadan', 'Malayer'),
('Hormozgan', 'Minab'),
('Isfahan', 'Khomeyni Shahr'),
('Kerman', 'Rafsanjan'),
('Razavi Khorasan', 'Neyshabur'),
('Khuzestan', 'Dezful'),
('Khuzestan', 'Abadan'),
('Lorestan', 'Borujerd'),
('Mazandaran', 'Babol'),
('Mazandaran', 'Qaemshahr'),
('Qazvin', 'Takestan'),
('Semnan', 'Shahrud'),
('Sistan and Baluchestan', 'Chabahar'),
('West Azerbaijan', 'Mahabad'),
('Yazd', 'Ardakan'),
('North Khorasan', 'Shirvan');

INSERT INTO City (province_name, city_name) VALUES
('Tehran', 'Shahr-e Qods'),
('Tehran', 'Varamin'),
('Tehran', 'Eslamshahr'),
('Tehran', 'Pakdasht');
