CREATE TABLE USER (
    USER_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    FIRST_NAME VARCHAR(100) NOT NULL,
    LAST_NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(255) UNIQUE,
    PHONE_NUMBER VARCHAR(20) UNIQUE,
    USER_TYPE ENUM('CUSTOMER', 'SUPPORT', 'ADMIN') NOT NULL,
    CITY VARCHAR(100),
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    REGISTRATION_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ACCOUNT_STATUS ENUM('ACTIVE', 'INACTIVE') NOT NULL DEFAULT 'ACTIVE',
    CHECK (
        EMAIL IS NOT NULL OR PHONE_NUMBER IS NOT NULL
    ),
    CHECK (
        EMAIL REGEXP '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$'
        OR EMAIL IS NULL
    ),
    CHECK (
        PHONE_NUMBER REGEXP '^[0-9]{10,15}$'
        OR PHONE_NUMBER IS NULL
    )
);

CREATE INDEX EMAIL_PASS_IDX
ON USER (EMAIL, PASSWORD_HASH);

INSERT INTO USER (
    USER_ID,
    FIRST_NAME,
    LAST_NAME,
    EMAIL,
    PHONE_NUMBER,
    USER_TYPE,
    CITY,
    PASSWORD_HASH,
    REGISTRATION_DATE,
    ACCOUNT_STATUS
) VALUES (
    1,
    'Ali',
    'Prs',
    'test@test.com',
    '09032948208',
    'CUSTOMER',
    'Ardebil',
    '11f0f5d8293fd1d996210e49d4642dadb6c1463ff9c47c888d45d4a1fb47eb6a',
    '2024-10-04 13:10:19',
    'ACTIVE'
);

INSERT INTO USER (
    USER_ID,
    FIRST_NAME,
    LAST_NAME,
    EMAIL,
    PHONE_NUMBER,
    USER_TYPE,
    CITY,
    PASSWORD_HASH,
    REGISTRATION_DATE,
    ACCOUNT_STATUS
) VALUES (
    2,
    'Mehdi',
    'Salman',
    'test2@test2.com',
    '09938634069',
    'CUSTOMER',
    'Tehran',
    '71a5f574ff500816cea8b3d5fd8555dbee7493773f04870217a111984c0fc13f',
    '2024-10-04 13:20:39',
    'ACTIVE'
);

SELECT 
    USER_ID, 
    FIRST_NAME, 
    LAST_NAME, 
    EMAIL, 
    PHONE_NUMBER, 
    USER_TYPE
FROM USER
WHERE FIRST_NAME = 'Ali';

SELECT 
    USER_ID, 
    FIRST_NAME, 
    LAST_NAME, 
    EMAIL, 
    PHONE_NUMBER, 
    USER_TYPE
FROM USER
WHERE PHONE_NUMBER = '09938634069';

