name: SQL Validation

on:
  push:
    branches:
      - '**' 
  pull_request:
    branches:
      - '**'  

jobs:
  validate-sql:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install sqlfluff
        run: |
          python -m pip install --upgrade pip
          pip install sqlfluff==2.3.5

      - name: Validate SQL files
        run: |
          echo "Validating SQL files..."
          sql_files=$(find . -type f -name "*.sql")
          if [ -z "$sql_files" ]; then
            echo "No SQL files found."
          else
            echo "Found SQL files:"
            echo "$sql_files"
            sqlfluff lint --dialect mysql $sql_files
          fi

      - name: Fix SQL files
        run: |
          echo "Fixing SQL files..."
          sql_files=$(find . -type f -name "*.sql")
          if [ -z "$sql_files" ]; then
            echo "No SQL files found."
          else
            echo "Found SQL files:"
            echo "$sql_files"
            sqlfluff fix --dialect mysql $sql_files
          fi
