name: Python MySQL Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: M.s28011384
          MYSQL_DATABASE: test_db
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pymysql

    - name: Wait for MySQL to be ready
      run: |
        while ! mysqladmin ping -h127.0.0.1 -P3306 -uroot -p"M.s28011384" --silent; do
          sleep 1
        done

    - name: Run tests
      env:
        MYSQL_HOST: 127.0.0.1
        MYSQL_USER: root
        MYSQL_PASSWORD: M.s28011384
        MYSQL_DATABASE: test_db
      run: |
        python -m pytest test.py -v
