name: Python MySQL Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
  MYSQL_DATABASE: test_db

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ${{ env.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: ${{ env.MYSQL_DATABASE }}
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pymysql

    - name: Wait for MySQL to be ready
      run: |
        for i in {1..30}; do
          if mysqladmin ping -h127.0.0.1 -P3306 -uroot -p"$MYSQL_ROOT_PASSWORD" --silent; then
            echo "MySQL is ready!"
            break
          fi
          echo "Waiting for MySQL... Attempt $i"
          sleep 2
        done

    - name: Verify database connection
      run: |
        mysql -h127.0.0.1 -P3306 -uroot -p"$MYSQL_ROOT_PASSWORD" -e "SHOW DATABASES;"

    - name: Create schema
      env:
        MYSQL_PWD: ${{ env.MYSQL_ROOT_PASSWORD }}
      run: |
        echo "Creating database schema..."
        for sql_file in city.sql user.sql terminal.sql transport_company.sql travel.sql vehicle_detail.sql train_detail.sql bus_detail.sql flight_detail.sql ticket.sql reservation.sql reservation_change.sql payment.sql report.sql; do
          echo "=== Executing create/$sql_file ==="
          mysql -h127.0.0.1 -P3306 -uroot "$MYSQL_DATABASE" < "create/$sql_file" && echo "Success" || { echo "Failed"; exit 1; }
          echo "=== Tables after execution ==="
          mysql -h127.0.0.1 -P3306 -uroot "$MYSQL_DATABASE" -e "SHOW TABLES;"
        done

    - name: Verify tables
      run: |
        mysql -h127.0.0.1 -P3306 -uroot -p"$MYSQL_ROOT_PASSWORD" "$MYSQL_DATABASE" -e "SHOW TABLES;"

    - name: Run tests
      env:
        MYSQL_HOST: 127.0.0.1
        MYSQL_USER: root
        MYSQL_PWD: ${{ env.MYSQL_ROOT_PASSWORD }}
        MYSQL_DATABASE: ${{ env.MYSQL_DATABASE }}
      run: |
        python -m pytest test.py -v
