name: SQL Validation

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main

jobs:
  validate-sql:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install sqlfluff
        run: |
          python -m pip install --upgrade pip
          pip install sqlfluff

      - name: Get changed SQL files
        id: changed-files
        uses: tj-actions/changed-files@v20
        with:
          files: |
            **/*.sql

      - name: Validate SQL files
        run: |
          if [ -n "${{ steps.changed-files.outputs.all_changed_files }}" ]; then
            echo "Validating SQL files..."
            sqlfluff lint ${{ steps.changed-files.outputs.all_changed_files }}
          else
            echo "No SQL files changed."
          fi
